apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: {{ .Values.keycloak.namespace }}
  labels:
    app: keycloak
    {{- include "secure-mcp.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: {{ .Values.gateway.aws.loadBalancerScheme }}
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: keycloak
  type: LoadBalancer
